import "../../MyProjects.css";

const MyProjects = () => {
  return (
    <>
      <h1>My Projects</h1>
      <ul className="project-list">

        {/* OLLIVANDERS */}
        <li className="project">
          <h3 className="project-title">
            <a href="https://ollivanders-exchange-dcb5920511b9.herokuapp.com/" target="_blank" rel="noopener noreferrer">
              Ollivanders Exchange
            </a>
          </h3>
          <div className="project-grid">
            <div className="project-media">
              <img
                src="https://images.pexels.com/photos/34585614/pexels-photo-34585614.jpeg"
                alt="Ollivanders Exchange screenshot"
                className="app-pic"
              />
            </div>
            <div className="project-content">
              <p>
                A Harry Potter–inspired Django app where users can create wizards, manage wands, and learn spells through a many-to-many model. Designed for immersive user interaction, similar to Pokemon Go.
              </p>
              <ul className="tech-tags">
                <li>Python</li>
                <li>Django</li>
                <li>PostgreSQL</li>
                <li>API Integration</li>
                <li>HTML/CSS</li>
              </ul>
            </div>
          </div>
        </li>

        {/* BLEEPR */}
        <li className="project">
          <h3 className="project-title">
            <a href="https://bleepr.netlify.app/" target="_blank" rel="noopener noreferrer">
              Bleepr
            </a>
          </h3>
          <div className="project-grid">
            <div className="project-media">
              <img
                src="https://images.pexels.com/photos/34585609/pexels-photo-34585609.jpeg"
                alt="Bleepr screenshot"
                className="app-pic"
              />
            </div>
            <div className="project-content">
              <p>
                A retro social media app inspired by early Twitter and Myspace. Users can post “bleeps,” comment, edit, delete, and filter by hashtags with editable profile pages. Each user has a profile page where they can post their about me, similar to Myspace. 
              </p>
              <ul className="tech-tags">
                <li>React</li>
                <li>Node.js</li>
                <li>Express</li>
                <li>MongoDB</li>
              </ul>
            </div>
          </div>
        </li>

        {/* PINPOINTS */}
        <li className="project">
          <h3 className="project-title">
            <a href="https://pinpoints-travel-app-8c41729fbe8e.herokuapp.com/" target="_blank" rel="noopener noreferrer">
              PinPoints Travel Application
            </a>
          </h3>
          <div className="project-grid">
            <div className="project-media">
              <img
                src="https://images.pexels.com/photos/34585611/pexels-photo-34585611.jpeg"
                alt="PinPoints screenshot"
                className="app-pic"
              />
            </div>
            <div className="project-content">
              <p>
                PinPoints is a travel-based social app for sharing real, community-driven insights about destinations. Users can sign up, post notes with photos, edit, and delete entries.
              </p>
              <ul className="tech-tags">
                <li>MongoDB</li>
                <li>Express</li>
                <li>EJS Templates</li>
                <li>Node.js</li>
                <li>Javascript</li>
                <li>RESTful Routes</li>
              </ul>
            </div>
          </div>
        </li>

        {/* WORDLE */}
        <li className="project">
          <h3 className="project-title">
            <a href="https://tpiol.github.io/wordle/" target="_blank" rel="noopener noreferrer">
              Wordle
            </a>
          </h3>
          <div className="project-grid">
            <div className="project-media">
              <img
                src="https://images.pexels.com/photos/34585612/pexels-photo-34585612.jpeg"
                alt="Wordle screenshot"
                className="app-pic"
              />
            </div>
            <div className="project-content">
              <p>
                Wordle is a browser game that allows each user six guesses to find the word automatically generated by the computer.
              </p>
              <ul className="tech-tags">
                <li>JavaScript</li>
                <li>HTML</li>
                <li>CSS</li>
              </ul>
            </div>
          </div>
        </li>

      </ul>
    </>
  );
};

export default MyProjects;
