const MyProjects = () => {
  return (
    <>
      <h1>My Projects</h1>
      <ul>
        <li>
          <h3>
            <a
              href="https://tpiol.github.io/wordle/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Wordle
            </a>
          </h3>
          <p>
            Wordle is a browser game that allows each user six guesses to guess the correct word automatically generated by the computer.
          </p>
        </li>

        <li>
          <h3>
            <a
              href="https://pinpoints-travel-app-8c41729fbe8e.herokuapp.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              PinPoints Travel Application
            </a>
          </h3>
          <p>
            PinPoints is a travel-based social game designed to help travelers share real, community-driven insights from all around the world.
            <br /><br />
            As a frequent traveler myself, I’ve often struggled with the lack of honest, up-to-date information about certain destinations. That’s why I created this app—it’s the kind of tool I wish existed during my own travels.
            <br /><br />
            With PinPoints, users can drop notes that include photos, tips, and must-know facts at specific locations, turning every adventure into a chance to help others. Whether it’s a hidden gem, a local warning, or just a favorite coffee shop, every note can help other travelers.
            <br /><br />
            Users can sign up for a new account, add a note, edit a note, and delete a note.
          </p>
        </li>

        <li>
          <h3>
            <a
              href="https://bleepr.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Bleepr
            </a>
          </h3>
          <p>
            Bleepr is a retro social media app, an homage to early Twitter and Myspace. Bleeprs can create, read, edit, and delete their own bleeps, as well as comment, edit, and delete comments.
            <br /><br />
            Bleeprs can also filter bleeps by hashtags and maintain profile pages with editable “About Me” sections.
            <br /><br />
            We built this project because we miss the sense of discovery and community engagement that came with social media before algorithm-driven feeds.
          </p>
        </li>

        <li>
          <h3>
            <a
              href="https://ollivanders-exchange-dcb5920511b9.herokuapp.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Ollivanders Exchange
            </a>
          </h3>
          <p>
            Ollivanders Exchange is a Harry Potter–inspired Django application where users can create and customize Wizards. Each Wizard has a detailed profile card, allowing users to add, update, or remove wands and learn new spells through a many-to-many relationship.
            <br /><br />
            Inspired by a love for the Wizarding World, this application immerses users in a Hogwarts-like experience where imagination brings the magic to life.
          </p>
        </li>
      </ul>
    </>
  );
};

export default MyProjects;